### ISSUE TITLE
Add an option to disable the progress indicator

### ISSUE THREAD

**Issue by vassilevsky** [essentialkaos/rbinstall#22]
It is necessary to be able to disable the indicator to avoid getting very long logs with every sprite of the indicator showing on a separate line.

**Comment by savonarola** [comment]
I suggest adding `-b` (`--batch`) switch :)

**Comment by andyone** [comment]
Feature added in [0.7.2](https://github.com/essentialkaos/rbinstall/releases/tag/v0.7.2)

@vassilevsky Use `-np`/`--no-progress` and `-nc`/`--no-color` flags with latest version (_available in KAOS repo_).

**Comment by vassilevsky** [comment]
Works as a charm ✨

```
==> default: Fetching 2.3.1-p0 (12.7MB)...
==> default: ✔ Checking sha1 checksum (< 1 second)
==> default: ✔ Unpacking 7z archive (1 second)
==> default: ✔ Installing bundler (28 seconds)
==> default: ✔ Rehashing (< 1 second)
==> default:
==> default: Version 2.3.1-p0 successfully installed!
```

Thank you very much 😘

**Comment by andyone** [comment]
Always welcome.
