### ISSUE TITLE
Uninstallation Ruby from the system

### ISSUE THREAD

**Issue by gongled** [essentialkaos/rbinstall#64]
### Feature Request

I suppose that would be great to be able to uninstall Ruby from the system. It might help if you need to remove installed Ruby by mistake. Also it a great chance to integrate RBInstall with SCM systems (such as Ansible, SaltStack etc.) which are already uses similar interfaces (like `present` or `absent` states in Ansible) for other package managers.

**Comment by andyone** [comment]
Hi! I never thought about version uninstalling. I will try to implement this feature, similarly to reinstall.

**Comment by andyone** [comment]
I've implemented it in 0.18.0 ([PR](https://github.com/essentialkaos/rbinstall/pull/63)). If you want, you can check it by installing 0.18.0 from `kaos-testing` repo.

**Comment by gongled** [comment]
@andyone Thanks. I have just checked RBInstall 0.18.0. It works great as usual.

**Comment by andyone** [comment]
Great! I’ll try to release this version shortly.

**Comment by andyone** [comment]
RBInstall 0.18.0 successfully released! 🍾
