### ISSUE TITLE
Unable to install Ruby 1.9.2-p* due to OpenSSL error

### ISSUE THREAD

**Issue by gongled** [essentialkaos/rbinstall#66]
### Bug report

**System info:**

* **Version used (`rbinstall --version`):** 0.18.0
* **OS (e.g. from `/etc/*-release`):** CentOS 6.9, CentOS 7.4.1708
* **Kernel (`uname -a`):** Linux f950a7f5e375 4.9.87-linuxkit-aufs (see official CentOS 7 Docker image with the name `centos:6` or `centos:7`)
* **Install tools:** yum/dnf

**Steps to reproduce:**

Install Ruby 1.9.2-p330 via `rbinstall` utility.

**Expected behavior:**

Ruby 1.9.2-p330 is successfully installed.

**Actual behavior:**

Ruby installation is failing. 

List of affected versions:
- 1.9.2-p180 (+railsexpress)
- 1.9.2-p290 (+railsexpress)
- 1.9.2-p318 (+railsexpress)
- 1.9.2-p320 (+railsexpress)

**Additional info:**

Here is the following content from `/tmp/rbinstall-fail.log` logging file:

```
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
SSL_read:: shutdown while in init
```

**Comment by andyone** [comment]
I've reconfigured our CDN infrastructure, and now installation should work fine. Sorry for the inconvenience.
