### ISSUE TITLE
Unable to install jRuby 1.6.* due to invalid gem option

### ISSUE THREAD

**Issue by gongled** [essentialkaos/rbinstall#67]
### Bug report

**System info:**

* **Version used (`rbinstall --version`):** 0.18.0
* **OS (e.g. from `/etc/*-release`):** CentOS 6.9, CentOS 7.4.1708
* **Kernel (`uname -a`):** Linux 0b4015909cd2 4.9.87-linuxkit-aufs (official Docker image for CentOS 6 and CentOS 7: `centos:6` and `centos:7`)
* **Install tools:** yum/dnf

**Steps to reproduce:**

Install jRuby 1.6.3 via `rbinstall` utility.

**Expected behavior:**

jRuby is successfully installed.

**Actual behavior:**

jRuby installation is failing.

**Additional info:**

List of affected versions:
- jruby-1.6.3
- jruby-1.6.4
- jruby-1.6.5.1
- jruby-1.6.6
- jruby-1.6.7
- jruby-1.6.8

Here is the content of `/tmp/rbinstall-fail.log` logging file:

```
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-document
```

**Comment by andyone** [comment]
It is impossible to fix this on the `rbinstall` side. Main problem — `rbinstall` can't update RubyGems to latest version due to disabled stack guard in `libjffi.so`.
