### ISSUE TITLE
Support versioning for gems

### ISSUE THREAD

**Issue by gongled** [essentialkaos/rbinstall#75]
### Feature Request

**Proposal:**

Add versioning support for `gems:install` in configuration file.

**Current behavior:**

`rbinstall` installs the latest available version from RubyGems.

**Desired behavior:**

`rbinstall` installs specified version from `gems:install` with widely-known RubyGem's versions specifiers.

**Use case:**

`rbinstall` installs gem `bundler` by default as it specified in configuration file. On January, 3rd Bundler development team released 2.0.0 version (and 2.0.1 one day after) which has a list of breaking changes. 

In particular, bundler 2.x is unable to install gems if `Gemfile.lock` contains version lower than 2.x., and vice-versa. It means that any application which relies on Bundler 1.x. will be broken after (re-)installation Ruby via `rbinstall` after January, 3.

Maybe we should install two versions of bundler with fixed versions of 1.x and 2.x. and let Bundler choose which version it should use during on dependencies installation.

**Comment by andyone** [comment]
Implemented in [0.20.0](https://github.com/essentialkaos/rbinstall/releases/tag/v0.20.0)
